# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger on semantic version tags, e.g., 1.2.3
    - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+' # Trigger on release candidate tags, e.g., v1.2.3-rc1
  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'
    - name: Build
      run: make build
    - name: Test
      run: make test
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_type == 'tag' # Only run this job for tags
    steps:
    - uses: actions/checkout@v3
    - name: Format Version from github.ref_name
      id: format_version
      run: |
        VERSION="${GITHUB_REF_NAME#v}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Log Version Information
      run: |
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "VERSION: ${{ env.VERSION }}"
    - uses: viamrobotics/build-action@v1
      with:
        # note: you can replace this line with 'version: ""' if you want to test the build process without deploying
        version: ${{ env.VERSION }}
        # version: ""
        ref: ${{ github.sha }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
